<?php

return [
    \App\Services\Status\UserStatusService::USER_NAME => \App\Commands\Registration\SetUserName::class,
    \App\Services\Status\UserStatusService::EDIT_USER_NAME => \App\Commands\Registration\SetUserName::class,
    \App\Services\Status\UserStatusService::SURNAME => \App\Commands\Registration\SetSurname::class,
    \App\Services\Status\UserStatusService::EDIT_SURNAME => \App\Commands\Registration\SetSurname::class,
    \App\Services\Status\UserStatusService::AGE => \App\Commands\Registration\SetAge::class,
    \App\Services\Status\UserStatusService::EDIT_AGE => \App\Commands\Registration\SetAge::class,
    \App\Services\Status\UserStatusService::PHONE_NUMBER => \App\Commands\Registration\SetPhoneNumber::class,
    \App\Services\Status\UserStatusService::ABOUT_ME => \App\Commands\Registration\SetAboutMe::class,
    \App\Services\Status\UserStatusService::EDIT_ABOUT_ME => \App\Commands\Registration\SetAboutMe::class,
    \App\Services\Status\UserStatusService::PHOTO => \App\Commands\Registration\SetPhoto::class,
    \App\Services\Status\UserStatusService::EDIT_PHOTO => \App\Commands\Registration\SetPhoto::class,
    \App\Services\Status\UserStatusService::HOBBY => \App\Commands\Registration\SetHobby::class,
    \App\Services\Status\UserStatusService::EDIT_HOBBY => \App\Commands\Registration\SetHobby::class,
    \App\Services\Status\UserStatusService::HAS_CAR => \App\Commands\Registration\SetHasCar::class,
    \App\Services\Status\UserStatusService::CAR_BRAND => \App\Commands\Registration\SetCarBrand::class,
    \App\Services\Status\UserStatusService::CAR_MODEL => \App\Commands\Registration\SetCarModel::class,
    \App\Services\Status\UserStatusService::CAR_NUMBER => \App\Commands\Registration\SetCarNumber::class,
    \App\Services\Status\UserStatusService::CAR_COLOR => \App\Commands\Registration\SetCarColor::class,

    \App\Services\Status\UserStatusService::ARRIVAL => \App\Commands\CreateRecord\ArrivalCity::class,
    \App\Services\Status\UserStatusService::ARRIVAL_SELECTING => \App\Commands\CreateRecord\ArrivalCity::class,
    \App\Services\Status\UserStatusService::ARRIVAL_STREET => \App\Commands\CreateRecord\ArrivalStreet::class,
    \App\Services\Status\UserStatusService::ARRIVAL_STREET_NUMBER => \App\Commands\CreateRecord\ArrivalStreetNumber::class,
    \App\Services\Status\UserStatusService::ARRIVAL_STREET_SELECTING => \App\Commands\CreateRecord\ArrivalStreet::class,
    \App\Services\Status\UserStatusService::DEPARTURE => \App\Commands\CreateRecord\DepartureCity::class,
    \App\Services\Status\UserStatusService::DEPARTURE_SELECTING => \App\Commands\CreateRecord\DepartureCity::class,
    \App\Services\Status\UserStatusService::DEPARTURE_STREET => \App\Commands\CreateRecord\DepartureStreet::class,
    \App\Services\Status\UserStatusService::DEPARTURE_STREET_NUMBER => \App\Commands\CreateRecord\DepartureStreetNumber::class,
    \App\Services\Status\UserStatusService::DEPARTURE_STREET_SELECTING => \App\Commands\CreateRecord\DepartureStreet::class,
    \App\Services\Status\UserStatusService::ARRIVAL_DATE => \App\Commands\CreateRecord\ArrivalDate::class,
    \App\Services\Status\UserStatusService::ARRIVAL_TIME => \App\Commands\CreateRecord\ArrivalTime::class,
    \App\Services\Status\UserStatusService::RECORD_PRICE => \App\Commands\CreateRecord\Price::class,
    \App\Services\Status\UserStatusService::RECORD_SPOTS => \App\Commands\CreateRecord\Spots::class,
    \App\Services\Status\UserStatusService::RECORD_DESCRIPTION => \App\Commands\CreateRecord\Description::class,


    \App\Services\Status\UserStatusService::SEARCH_ARRIVAL => \App\Commands\SearchRecord\ArrivalCity::class,
    \App\Services\Status\UserStatusService::SEARCH_ARRIVAL_SELECTING => \App\Commands\SearchRecord\ArrivalCity::class,
    \App\Services\Status\UserStatusService::SEARCH_ARRIVAL_STREET => \App\Commands\SearchRecord\ArrivalStreet::class,
    \App\Services\Status\UserStatusService::SEARCH_ARRIVAL_STREET_SELECTING => \App\Commands\SearchRecord\ArrivalStreet::class,
    \App\Services\Status\UserStatusService::SEARCH_DEPARTURE => \App\Commands\SearchRecord\DepartureCity::class,
    \App\Services\Status\UserStatusService::SEARCH_DEPARTURE_SELECTING => \App\Commands\SearchRecord\DepartureCity::class,
    \App\Services\Status\UserStatusService::SEARCH_DEPARTURE_STREET => \App\Commands\SearchRecord\DepartureStreet::class,
    \App\Services\Status\UserStatusService::SEARCH_DEPARTURE_STREET_SELECTING => \App\Commands\SearchRecord\DepartureStreet::class,
    \App\Services\Status\UserStatusService::SEARCH_ARRIVAL_DATE => \App\Commands\SearchRecord\ArrivalDate::class,
    \App\Services\Status\UserStatusService::SEARCH_ARRIVAL_TIME => \App\Commands\SearchRecord\ArrivalTime::class,
    \App\Services\Status\UserStatusService::SEARCH_RECORD_SPOTS => \App\Commands\SearchRecord\Spots::class,
    \App\Services\Status\UserStatusService::SEARCH_DEPARTURE_STREET_NUMBER => \App\Commands\SearchRecord\DepartureStreetNumber::class,
    \App\Services\Status\UserStatusService::SEARCH_ARRIVAL_STREET_NUMBER => \App\Commands\SearchRecord\ArrivalStreetNumber::class,

    \App\Services\Status\UserStatusService::VERIFY_PROFILE => \App\Commands\Verify\VerifyProfile::class,
    \App\Services\Status\UserStatusService::VERIFY_CAR_DATA => \App\Commands\Verify\VerifyCarData::class,
    \App\Services\Status\UserStatusService::VERIFY_CAR_PHOTO_IN => \App\Commands\Verify\VerifyCarPhotoIn::class,
];
