<?php

namespace App\Services\Status;

/**
 * Class UserStatusService store all user statuses
 * @package App\Services
 */
class UserStatusService {

    const NEW = 'NEW';
    const DONE = 'DONE';
    const EDIT_USER_NAME = 'EDIT_USER_NAME';
    const USER_NAME = 'USER_NAME';
    const EDIT_SURNAME = 'EDIT_SURNAME';
    const SURNAME = 'SURNAME';
    const EDIT_AGE = 'EDIT_AGE';
    const AGE = 'AGE';
    const PHONE_NUMBER = 'PHONE_NUMBER';
    const EDIT_ABOUT_ME = 'EDIT_ABOUT_ME';
    const ABOUT_ME = 'ABOUT_ME';
    const EDIT_HOBBY = 'EDIT_HOBBY';
    const HOBBY = 'HOBBY';
    const EDIT_PHOTO = 'EDIT_PHOTO';
    const PHOTO = 'PHOTO';

    const HAS_CAR = 'HAS_CAR';
    const CAR_MODEL = 'CAR_MODEL';
    const CAR_BRAND = 'CAR_BRAND';
    const CAR_NUMBER = 'CAR_NUMBER';
    const CAR_COLOR = 'CAR_COLOR';

    const ARRIVAL = 'ARRIVAL';
    const SEARCH_ARRIVAL = 'SEARCH_ARRIVAL';
    const ARRIVAL_STREET = 'ARRIVAL_STREET';
    const ARRIVAL_STREET_NUMBER = 'ARRIVAL_STREET_NUMBER';
    const SEARCH_ARRIVAL_STREET_NUMBER = 'SEARCH_ARRIVAL_STREET_NUMBER';
    const SEARCH_ARRIVAL_STREET = 'SEARCH_ARRIVAL_STREET';
    const ARRIVAL_SELECTING = 'ARRIVAL_SELECTING';
    const SEARCH_ARRIVAL_SELECTING = 'SEARCH_ARRIVAL_SELECTING';
    const ARRIVAL_STREET_SELECTING = 'ARRIVAL_STREET_SELECTING';
    const SEARCH_ARRIVAL_STREET_SELECTING = 'SEARCH_ARRIVAL_STREET_SELECTING';

    const DEPARTURE = 'DEPARTURE';
    const SEARCH_DEPARTURE = 'SEARCH_DEPARTURE';
    const DEPARTURE_SELECTING = 'DEPARTURE_SELECTING';
    const SEARCH_DEPARTURE_SELECTING = 'SEARCH_DEPARTURE_SELECTING';
    const DEPARTURE_STREET = 'DEPARTURE_STREET';
    const DEPARTURE_STREET_NUMBER = 'DEPARTURE_STREET_NUMBER';
    const SEARCH_DEPARTURE_STREET_NUMBER = 'SEARCH_DEPARTURE_STREET_NUMBER';
    const SEARCH_DEPARTURE_STREET = 'SEARCH_DEPARTURE_STREET';
    const DEPARTURE_STREET_SELECTING = 'DEPARTURE_STREET_SELECTING';
    const SEARCH_DEPARTURE_STREET_SELECTING = 'SEARCH_DEPARTURE_STREET_SELECTING';

    const ARRIVAL_DATE = 'ARRIVAL_DATE';
    const SEARCH_ARRIVAL_DATE = 'SEARCH_ARRIVAL_DATE';
    const ARRIVAL_TIME = 'ARRIVAL_TIME';
    const SEARCH_ARRIVAL_TIME = 'SEARCH_ARRIVAL_TIME';
    const RECORD_PRICE = 'RECORD_PRICE';
    const RECORD_SPOTS = 'RECORD_SPOTS';
    const SEARCH_RECORD_SPOTS = 'SEARCH_RECORD_SPOTS';
    const RECORD_DESCRIPTION = 'RECORD_DESCRIPTION';

    const VERIFY_PROFILE = 'VERIFY_PROFILE';
    const VERIFY_CAR_DATA = 'VERIFY_CAR_DATA';
    const VERIFY_CAR_PHOTO_IN = 'VERIFY_CAR_PHOTO_IN';

}